version: '3.9'
volumes:
  node_modules:
services:
  node_ts:
    build:
      context: .
    volumes:
      - .:/app
    container_name: node_ts
    environment:
      - PORT=3000
      - PG_HOST=node_ts_db
      - PG_PORT=5432
      - PG_USERNAME=postgres
      - PG_DATABASE=clean-arch-node-ts
      - PG_PASSWORD=admin
    ports:
      - '13000:3000'
      - '9228:9228'
    command: npm run dev
  node_ts_db:
    image: postgres:alpine
    container_name: node_ts_db
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: clean-arch-node-ts
    volumes:
      - ${HOME}/docker/postgresql/node_ts_db:/var/lib/postgresql
    ports:
      - "5434:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
