version: '3.9'
volumes:
  node_modules:
services:
  crud_node:
    build:
      context: .
    volumes:
      - .:/app
      - /app/node_modules
    container_name: crud_node
    env_file:
      - .env.docker
    ports:
      - '13000:3000'
      - '9228:9228'
    command: npm run dev:debug
  terminal:
    tty: true
    stdin_open: true
    build:
      context: .
    volumes:
      - .:/app
      - /app/node_modules
    container_name: terminal
    env_file:
      - .env.docker
    ports:
      - '13000:3000'
      - '9228:9228'
    depends_on:
      - crud_node_db
  crud_node_db:
    image: postgres:alpine
    container_name: crud_node_db
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: crud_node
    volumes:
      - ./.docker/crud_node_db:/var/lib/postgresql
    ports:
      - "5434:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
