version: '3.9'
volumes:
  node_modules:
services:
  node_ts:
    build:
      context: .
    volumes:
      - .:/app
      - /app/node_modules
    container_name: node_ts
    env_file:
      - .env.docker
    ports:
      - '13000:3000'
      - '9228:9228'
    command: npm run dev
  node_ts_terminal:
    tty: true
    stdin_open: true
    build:
      context: .
    volumes:
      - .:/app
      - /app/node_modules
    container_name: node_ts_terminal
    env_file:
      - .env.docker
    ports:
      - '13000:3000'
      - '9228:9228'
    depends_on:
      - node_ts_db
  node_ts_db:
    image: postgres:alpine
    container_name: node_ts_db
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: crud_node
    volumes:
      - ./.docker/node_ts_db:/var/lib/postgresql
    ports:
      - "5434:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
